// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallLLM(arg1) {
  return window['go']['main']['App']['CallLLM'](arg1);
}

export function CancelLLMRequest() {
  return window['go']['main']['App']['CancelLLMRequest']();
}
